name: 'Create or Update Tag and Release'

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner que executará os jobs
        type: string
        required: false
        default: ubuntu-latest
      ref-name:
        description: Nome da branch de release
        type: string
        required: false
        default: ${{ github.ref_name }}
      update-if-exists:
        description: Atualiza a tag e a release caso já existam
        type: boolean
        required: false
        default: true
    
    secrets:
      PAT:
        required: true

jobs:
  tag-release:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      
      - name: Set Up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]'
          git remote set-url origin https://renanphellip:${{ secrets.PAT }}@github.com/${{ github.repository }}.git/
      
      - name: Create or Update Tag
        run: |
          TAG_NAME="${{ inputs.ref-name }}"
          git tag -a "${TAG_NAME}" -m "Release ${TAG_NAME}" 2>/dev/null || git tag -f -a "${TAG_NAME}" -m "Release ${TAG_NAME}"
          git push origin --tags --force
      
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.PAT }}
          allowUpdates: ${{ inputs.update-if-exists }}
          tag: ${{ inputs.ref-name }}
          name: Release ${{ inputs.ref-name }}
          generateReleaseNotes: true
          prerelease: true
